"use client";

import {useEffect, useState} from "react";
import Link from "next/link";
import {useParams, useRouter} from "next/navigation";
import {
	ArrowLeftIcon,
	BoxesIcon,
	CheckIcon,
	CodeIcon,
	CopyIcon,
	DownloadIcon,
	FileTextIcon,
	LinkIcon,
	Share2Icon,
	SparklesIcon,
} from "lucide-react";

import {AppShell} from "@/components/AppShell";
import {Button} from "@/components/lib/shadcn/ui/button";
import {cn} from "@/components/lib/shadcn/lib/utils";
import {ApiError, apiFetch, downloadFile} from "@/lib/api";
import {clearBearerToken} from "@/lib/authClient";

interface CollectionDetail {
	id: string;
	name: string;
	currentVersionId: string | null;
	shareEnabled: boolean;
	shareSlug: string | null;
	createdAt: string;
	updatedAt: string;
	latestVersion: {
		id: string;
		openapiDoc: Record<string, unknown> | null;
		aiProvider: string | null;
		aiModel: string | null;
		createdAt: string;
		sourceInput: {
			kind: string;
			url?: string;
			platforms: string[];
			detectedFormat?: string;
			extraPrompt?: string;
		} | null;
	} | null;
}

interface CreditsResponse {
	balance: number;
}

export default function CollectionDetailPage() {
	const router = useRouter();
	const params = useParams<{id: string}>();
	const [detail, setDetail] = useState<CollectionDetail | null>(null);
	const [balance, setBalance] = useState<number | null>(null);
	const [error, setError] = useState<string | null>(null);

	useEffect(() => {
		let cancelled = false;

		async function load() {
			try {
				const [data, bal] = await Promise.all([
					apiFetch<CollectionDetail>(`/collections/${params.id}`),
					apiFetch<CreditsResponse>(`/credits/balance`),
				]);
				if (!cancelled) {
					setDetail(data);
					setBalance(bal.balance);
				}
			} catch (e) {
				if (cancelled) return;
				if (e instanceof ApiError && e.status === 401) {
					clearBearerToken();
					router.replace("/login");
					return;
				}
				setError(e instanceof Error ? e.message : "Failed to load");
			}
		}

		void load();
		return () => {
			cancelled = true;
		};
	}, [params.id, router]);

	const ready = !!detail?.latestVersion?.openapiDoc;

	return (
		<AppShell
			title={
				<span className="flex items-center gap-3">
					<Link
						href="/dashboard"
						className="rounded-lg p-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
						aria-label="Back to dashboard"
					>
						<ArrowLeftIcon className="h-4 w-4" />
					</Link>
					{detail?.name || "Loading…"}
				</span>
			}
			subtitle={
				detail
					? `Created ${new Date(detail.createdAt).toLocaleString()}`
					: undefined
			}
			balance={balance}
			actions={
				ready && detail ? (
					<DownloadGroup
						collectionId={detail.id}
						collectionName={detail.name}
						platforms={detail.latestVersion?.sourceInput?.platforms ?? []}
					/>
				) : undefined
			}
		>
			{error && (
				<div className="mb-4 rounded-xl border border-destructive/40 bg-destructive/10 px-4 py-3 text-sm">
					{error}
				</div>
			)}

			{detail && !ready && (
				<div className="card-elevated flex items-center gap-3 px-5 py-4">
					<div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary/15 text-primary">
						<SparklesIcon className="h-5 w-5" />
					</div>
					<div>
						<p className="text-sm font-medium">Still generating</p>
						<p className="mt-0.5 text-xs text-muted-foreground">
							Head back to the dashboard to see live progress.
						</p>
					</div>
				</div>
			)}

			{detail && ready && detail.latestVersion && (
				<div className="grid grid-cols-1 gap-4 lg:grid-cols-3">
					<MetaCard
						icon={<FileTextIcon className="h-4 w-4" />}
						label="Source format"
						value={detail.latestVersion.sourceInput?.detectedFormat ?? "—"}
						tone="primary"
					/>
					<MetaCard
						icon={<LinkIcon className="h-4 w-4" />}
						label="Source URL"
						value={detail.latestVersion.sourceInput?.url ?? "—"}
						truncate
					/>
					<MetaCard
						icon={<SparklesIcon className="h-4 w-4" />}
						label="Generated by"
						value={
							detail.latestVersion.aiProvider
								? `${detail.latestVersion.aiProvider} · ${detail.latestVersion.aiModel}`
								: "—"
						}
						tone="warning"
					/>

					<section className="card-elevated lg:col-span-3">
						<div className="flex items-center justify-between border-b border-border px-5 py-4">
							<div className="flex items-center gap-2 text-sm font-medium">
								<CodeIcon className="h-4 w-4 text-muted-foreground" />
								OpenAPI document
							</div>
							<span className="rounded-full bg-success/15 px-2 py-0.5 text-[10px] font-medium uppercase tracking-wider text-success">
								Ready
							</span>
						</div>
						<pre className="max-h-[60vh] overflow-auto px-5 py-4 font-mono text-xs leading-relaxed">
							{JSON.stringify(detail.latestVersion.openapiDoc, null, 2)}
						</pre>
					</section>

					<section className="card-elevated relative col-span-1 overflow-hidden p-5 lg:col-span-3">
						<div className="absolute inset-x-0 top-0 h-24 bg-gradient-to-b from-primary/15 to-transparent" />
						<div className="relative flex flex-wrap items-center justify-between gap-3">
							<div className="flex items-center gap-3">
								<div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary/15 text-primary">
									<BoxesIcon className="h-5 w-5" />
								</div>
								<div>
									<p className="text-sm font-medium">Download a collection</p>
									<p className="text-xs text-muted-foreground">
										Postman gets a native v2.1 collection. Other targets get the
										OpenAPI JSON — import via each tool&apos;s OpenAPI option.
									</p>
								</div>
							</div>
						</div>
					</section>

					<ShareCard
						collectionId={detail.id}
						shareEnabled={detail.shareEnabled}
						shareSlug={detail.shareSlug}
						onChange={(next) =>
							setDetail((prev) =>
								prev
									? {
											...prev,
											shareEnabled: next.shareEnabled,
											shareSlug: next.shareSlug,
										}
									: prev
							)
						}
					/>
				</div>
			)}
		</AppShell>
	);
}

function ShareCard({
	collectionId,
	shareEnabled,
	shareSlug,
	onChange,
}: {
	collectionId: string;
	shareEnabled: boolean;
	shareSlug: string | null;
	onChange: (next: {shareEnabled: boolean; shareSlug: string | null}) => void;
}) {
	const [busy, setBusy] = useState(false);
	const [copied, setCopied] = useState(false);
	const [error, setError] = useState<string | null>(null);

	// Public share URL points at the FE viewer page (which calls the API
	// in turn). That way the recipient sees a UI with download buttons,
	// not a raw JSON metadata response.
	const shareUrl =
		shareEnabled && shareSlug && typeof window !== "undefined"
			? `${window.location.origin}/share/${shareSlug}`
			: null;

	async function toggle(enabled: boolean) {
		setBusy(true);
		setError(null);
		try {
			const res = await apiFetch<{
				shareEnabled: boolean;
				shareSlug: string | null;
			}>(`/collections/${collectionId}/share`, {
				method: "POST",
				body: JSON.stringify({enabled}),
			});
			onChange(res);
		} catch (e) {
			setError(e instanceof Error ? e.message : "Failed to update share");
		} finally {
			setBusy(false);
		}
	}

	async function copyLink() {
		if (!shareUrl) return;
		try {
			await navigator.clipboard.writeText(shareUrl);
			setCopied(true);
			setTimeout(() => setCopied(false), 1500);
		} catch {
			setError("Couldn't copy to clipboard.");
		}
	}

	return (
		<section className="card-elevated relative overflow-hidden p-5 lg:col-span-3">
			<div className="absolute inset-x-0 top-0 h-24 bg-gradient-to-b from-warning/15 to-transparent" />
			<div className="relative flex flex-wrap items-start justify-between gap-3">
				<div className="flex items-start gap-3">
					<div className="flex h-10 w-10 items-center justify-center rounded-xl bg-warning/15 text-warning">
						<Share2Icon className="h-5 w-5" />
					</div>
					<div>
						<p className="text-sm font-medium">Public share link</p>
						<p className="text-xs text-muted-foreground">
							Anyone with the link can download this collection. Turning sharing
							off rotates the slug — old links die immediately.
						</p>
					</div>
				</div>
				<Button
					variant={shareEnabled ? "outline" : "default"}
					size="sm"
					disabled={busy}
					onClick={() => toggle(!shareEnabled)}
				>
					{busy ? "…" : shareEnabled ? "Disable sharing" : "Enable sharing"}
				</Button>
			</div>

			{shareEnabled && shareUrl && (
				<div className="relative mt-4 flex items-center gap-2">
					<div className="flex min-w-0 flex-1 items-center gap-2 rounded-md border border-border bg-background px-3 py-2">
						<LinkIcon className="h-3.5 w-3.5 shrink-0 text-muted-foreground" />
						<code className="truncate text-xs">{shareUrl}</code>
					</div>
					<Button
						variant="outline"
						size="sm"
						onClick={copyLink}
						className="gap-1.5"
					>
						{copied ? (
							<>
								<CheckIcon className="h-3.5 w-3.5 text-success" />
								Copied
							</>
						) : (
							<>
								<CopyIcon className="h-3.5 w-3.5" />
								Copy
							</>
						)}
					</Button>
				</div>
			)}

			{error && (
				<p className="relative mt-2 text-xs text-destructive">{error}</p>
			)}
		</section>
	);
}

function MetaCard({
	icon,
	label,
	value,
	tone,
	truncate,
}: {
	icon: React.ReactNode;
	label: string;
	value: string;
	tone?: "primary" | "warning";
	truncate?: boolean;
}) {
	const toneStyles = tone
		? tone === "primary"
			? "text-primary"
			: "text-warning"
		: "text-muted-foreground";
	return (
		<div className="card-elevated p-4">
			<div className="flex items-center gap-2 text-xs uppercase tracking-wider text-muted-foreground">
				<span className={cn(toneStyles)}>{icon}</span>
				{label}
			</div>
			<p
				className={cn("mt-2 text-sm font-medium", truncate && "truncate")}
				title={truncate ? value : undefined}
			>
				{value}
			</p>
		</div>
	);
}

const PLATFORM_LABELS: Record<string, string> = {
	postman: "Postman",
	bruno: "Bruno",
	hoppscotch: "Hoppscotch",
	thunder: "Thunder Client",
};

function DownloadGroup({
	collectionId,
	collectionName,
	platforms,
}: {
	collectionId: string;
	collectionName: string;
	platforms: string[];
}) {
	const [busy, setBusy] = useState<string | null>(null);
	const [error, setError] = useState<string | null>(null);

	if (platforms.length === 0) return null;

	function fallbackFilename(format: string): string {
		const safeName =
			collectionName.replace(/[^a-zA-Z0-9-_]+/g, "_") || "collection";
		return format === "postman"
			? `${safeName}.postman_collection.json`
			: `${safeName}.openapi.json`;
	}

	async function handleDownload(format: string) {
		setBusy(format);
		setError(null);
		try {
			await downloadFile(
				`/collections/${collectionId}/download/${format}`,
				fallbackFilename(format)
			);
		} catch (e) {
			setError(e instanceof Error ? e.message : "Download failed");
		} finally {
			setBusy(null);
		}
	}

	return (
		<div className="flex flex-col items-end gap-1.5">
			<div className="flex flex-wrap gap-2">
				{platforms.map((p) => (
					<Button
						key={p}
						variant="outline"
						size="sm"
						className="gap-1.5"
						disabled={busy !== null}
						onClick={() => handleDownload(p)}
					>
						<DownloadIcon className="h-3.5 w-3.5" />
						{busy === p ? "…" : (PLATFORM_LABELS[p] ?? p)}
					</Button>
				))}
			</div>
			{error && <p className="text-xs text-destructive">{error}</p>}
		</div>
	);
}
